<a href="https://colab.research.google.com/github/Yashwanthyashu9110/ML_23AG1A66f0/blob/main/Data_processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
data=pd.read_csv('name-age-gender-marks-city - Sheet1.csv')
data.head()

   Name    Age Gender  Marks      City
0  Alice  18.0      F   85.0    London
1    Bob   NaN      M   90.0  New york
2  David  17.0      M   72.0    Sydney
3  Cathy  19.0      F   95.0       NaN
4    Eva  18.0      F    NaN    London

In [10]:
data.fillna({
    'Age':data['Age'].mean(),
    'Marks':data["Marks"].mean(),
    'City':'Unknown'
},inplace=True)
print(data)

   Name    Age Gender  Marks      City
0  Alice  18.0      F   85.0    London
1    Bob  18.0      M   90.0  New york
2  David  17.0      M   72.0    Sydney
3  Cathy  19.0      F   95.0   Unknown
4    Eva  18.0      F   85.5    London

In [11]:
import pandas as pd

# Create example data including duplicates
data = {
    'Name': ['Alice', 'Bob', 'Alice'],
    'Age': [18, 18, 18],
    'Gender': ['F', 'M', 'F'],
    'Marks': [85, 90, 85]
}

df = pd.DataFrame(data)

print("Original Data:")
print(df)

# Remove duplicates across all columns
df_no_duplicates = df.drop_duplicates()

print("\nAfter Removing Duplicates:")
print(df_no_duplicates)

Original Data:
    Name  Age Gender  Marks
0  Alice   18      F     85
1    Bob   18      M     90
2  Alice   18      F     85

After Removing Duplicates:
    Name  Age Gender  Marks
0  Alice   18      F     85
1    Bob   18      M     90